/*
=========================================================
Problem: Next Permutation
Difficulty: Medium

My Approach:
- Traversed the array from right to left to find the first
  index where the sequence stops decreasing. This index is
  the pivot (break index).
- If no pivot exists, the array is the last permutation, so
  reversing the entire array produces the smallest
  permutation.
- Otherwise, searched from the end of the array to find the
  first element greater than the pivot.
- Swapped the pivot with that element.
- Reversed the suffix after the pivot to obtain the next
  lexicographically smallest permutation.

Key Concept(s):
- Greedy Observation
- Array Manipulation
- Lexicographical Ordering
- Reverse Technique

Time Complexity:
O(n)

Space Complexity:
O(1)

What I Learned:
- The next permutation can be generated by modifying the
  smallest possible suffix.
- The suffix after the pivot is always in decreasing order,
  allowing it to be reversed into ascending order after the
  swap.
- Understanding the reasoning behind the algorithm is more
  important than memorizing its steps.

Revision Note:
1. Find the pivot from the right.
2. If no pivot exists, reverse the entire array.
3. Find the first element greater than the pivot from the
   right.
4. Swap the two elements.
5. Reverse the suffix after the pivot.
=========================================================
*/
class Solution {
public:
    void nextPermutation(vector<int>& nums) {
        int breakindex = -1;
        for (int i = nums.size() - 2; i >= 0; i--) {
            if (nums[i + 1] > nums[i]) {
                breakindex = i;
                break;
            }
        }
        if (breakindex == -1)
            reverse(nums.begin(), nums.end());
        else {
            for (int i = nums.size() - 1; i >= 0; i--) {
                if (nums[i] > nums[breakindex]) {
                    swap(nums[i], nums[breakindex]);
                    break;
                }
            }
            reverse(nums.begin() + breakindex + 1, nums.end());
        }
    }
};